version: '3.1'
services:
  springboot:
    image: saurabhefm/springboot-mongo
    restart: always
    container_name: springboot
    ports:
      - 9090:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 20s
      restart_policy:
        condition: on-failure
    
  db:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
    restart: always
    
volumes:
  data:
  data-bkp:

